### ISSUE TITLE
missing argument for parameter 'detent' in call

### ISSUE THREAD

**Issue by aetherwu** [Polenoso/BottomSheetSUI#1]
With code:

```
import BottomSheetSUI

...

BottomSheetView(detents: [.small, .medium, .large]) {
    Text("This is an example content")
}

```
Shows error:

`
missing argument for parameter 'detent' in call
`

**Comment by Polenoso** [comment]
Thanks for opening the issue!

I’ll fix the documentation.

I introduced a change to Bind a detent to be able to change the value from the bottom Sheet container.

I’ll let you know once done.
